### Successful login
POST https://flask-login-lab2.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}

### Failed login
POST https://flask-login-lab2.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrongpass"
}
